/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellWorkflowsRouteImport } from './routes/_shell.workflows'
import { Route as ShellTerminalsRouteImport } from './routes/_shell.terminals'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellDecisionsRouteImport } from './routes/_shell.decisions'
import { Route as ShellWorkflowsWorkflowIdRouteImport } from './routes/_shell.workflows.$workflowId'
import { Route as ShellSessionsSessionIdRouteImport } from './routes/_shell.sessions.$sessionId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell.projects.$projectId'
import { Route as ShellProjectsProjectIdSettingsRouteImport } from './routes/_shell.projects.$projectId_.settings'
import { Route as ShellProjectsProjectIdSessionsSessionIdRouteImport } from './routes/_shell.projects.$projectId_.sessions.$sessionId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkflowsRoute = ShellWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTerminalsRoute = ShellTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDecisionsRoute = ShellDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkflowsWorkflowIdRoute =
  ShellWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => ShellWorkflowsRoute,
  } as any)
const ShellSessionsSessionIdRoute = ShellSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdSettingsRoute =
  ShellProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProjectsProjectIdSessionsSessionIdRoute =
  ShellProjectsProjectIdSessionsSessionIdRouteImport.update({
    id: '/projects/$projectId_/sessions/$sessionId',
    path: '/projects/$projectId/sessions/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/decisions': typeof ShellDecisionsRoute
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/workflows': typeof ShellWorkflowsRouteWithChildren
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/workflows/$workflowId': typeof ShellWorkflowsWorkflowIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/decisions': typeof ShellDecisionsRoute
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/workflows': typeof ShellWorkflowsRouteWithChildren
  '/': typeof ShellIndexRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/workflows/$workflowId': typeof ShellWorkflowsWorkflowIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/decisions': typeof ShellDecisionsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/terminals': typeof ShellTerminalsRoute
  '/_shell/workflows': typeof ShellWorkflowsRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/_shell/workflows/$workflowId': typeof ShellWorkflowsWorkflowIdRoute
  '/_shell/projects/$projectId_/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/_shell/projects/$projectId_/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decisions'
    | '/settings'
    | '/terminals'
    | '/workflows'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/workflows/$workflowId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/decisions'
    | '/settings'
    | '/terminals'
    | '/workflows'
    | '/'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/workflows/$workflowId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sessions/$sessionId'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/decisions'
    | '/_shell/settings'
    | '/_shell/terminals'
    | '/_shell/workflows'
    | '/_shell/'
    | '/_shell/projects/$projectId'
    | '/_shell/sessions/$sessionId'
    | '/_shell/workflows/$workflowId'
    | '/_shell/projects/$projectId_/settings'
    | '/_shell/projects/$projectId_/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workflows': {
      id: '/_shell/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof ShellWorkflowsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terminals': {
      id: '/_shell/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof ShellTerminalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/decisions': {
      id: '/_shell/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof ShellDecisionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/workflows/$workflowId': {
      id: '/_shell/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof ShellWorkflowsWorkflowIdRouteImport
      parentRoute: typeof ShellWorkflowsRoute
    }
    '/_shell/sessions/$sessionId': {
      id: '/_shell/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof ShellSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/settings': {
      id: '/_shell/projects/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ShellProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/sessions/$sessionId': {
      id: '/_shell/projects/$projectId_/sessions/$sessionId'
      path: '/projects/$projectId/sessions/$sessionId'
      fullPath: '/projects/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ShellProjectsProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellWorkflowsRouteChildren {
  ShellWorkflowsWorkflowIdRoute: typeof ShellWorkflowsWorkflowIdRoute
}

const ShellWorkflowsRouteChildren: ShellWorkflowsRouteChildren = {
  ShellWorkflowsWorkflowIdRoute: ShellWorkflowsWorkflowIdRoute,
}

const ShellWorkflowsRouteWithChildren = ShellWorkflowsRoute._addFileChildren(
  ShellWorkflowsRouteChildren,
)

interface ShellRouteChildren {
  ShellDecisionsRoute: typeof ShellDecisionsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTerminalsRoute: typeof ShellTerminalsRoute
  ShellWorkflowsRoute: typeof ShellWorkflowsRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
  ShellSessionsSessionIdRoute: typeof ShellSessionsSessionIdRoute
  ShellProjectsProjectIdSettingsRoute: typeof ShellProjectsProjectIdSettingsRoute
  ShellProjectsProjectIdSessionsSessionIdRoute: typeof ShellProjectsProjectIdSessionsSessionIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDecisionsRoute: ShellDecisionsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTerminalsRoute: ShellTerminalsRoute,
  ShellWorkflowsRoute: ShellWorkflowsRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
  ShellSessionsSessionIdRoute: ShellSessionsSessionIdRoute,
  ShellProjectsProjectIdSettingsRoute: ShellProjectsProjectIdSettingsRoute,
  ShellProjectsProjectIdSessionsSessionIdRoute:
    ShellProjectsProjectIdSessionsSessionIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
