package daemonmeta

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/uuid"
)

// P9 — the three identities AO must never confuse.
//
//   - INSTALLATION identity: one AO data dir. Created once, the first time a
//     daemon starts on that data dir, and never regenerated by a read. It is
//     what lets a runtime (a tmux session on a shared socket) or a run-file be
//     attributed to THIS installation rather than to another profile, sandbox
//     or test data dir that happens to use the same machine.
//   - DAEMON INSTANCE identity: one daemon process lifetime. A fresh id per
//     boot, so a run-file or a runtime stamp left by an earlier incarnation is
//     distinguishable from the daemon serving now. Provenance only: a new
//     daemon must still be able to adopt a worker an earlier one launched.
//   - WORKER RUNTIME identity: one launch of one session (owner token + tmux
//     incarnation, see domain.SessionRuntimeOwnerToken). Never derived from
//     either of the two above.
//
// None of them is a PID. A PID is reused by the operating system and proves
// nothing about ownership.

// InstallationIDFile is the file, inside the data dir, holding the
// installation identity. It is deliberately not telemetry_install_id: that one
// belongs to an opt-in telemetry pipeline whose lifecycle (reset, opt-out) must
// never be able to change what AO believes it owns.
const InstallationIDFile = "installation_id"

const installationIDPrefix = "aoi-"

// ValidInstallationID reports whether id has the shape LoadOrCreateInstallationID
// writes. A malformed value is never "repaired" by generating a new one: a new
// identity would silently disown every runtime the old one stamped.
func ValidInstallationID(id string) bool {
	rest, ok := strings.CutPrefix(id, installationIDPrefix)
	if !ok {
		return false
	}
	_, err := uuid.Parse(rest)
	return err == nil
}

// LoadOrCreateInstallationID returns the installation identity for dataDir,
// creating it exactly once.
//
// Creation is exclusive (O_EXCL): two daemons racing on a fresh data dir cannot
// both mint an identity — the loser re-reads the winner's. A file that exists
// but is unreadable or malformed is an ERROR, never a reason to mint another:
// callers run without an installation stamp rather than under a false one.
func LoadOrCreateInstallationID(dataDir string) (string, error) {
	if strings.TrimSpace(dataDir) == "" {
		return "", errors.New("daemonmeta: installation identity requires a data dir")
	}
	path := filepath.Join(dataDir, InstallationIDFile)
	if id, err := readInstallationID(path); err == nil {
		return id, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}
	if err := os.MkdirAll(dataDir, 0o750); err != nil {
		return "", fmt.Errorf("daemonmeta: create data dir: %w", err)
	}
	id := installationIDPrefix + uuid.NewString()
	// Written COMPLETE to a private temp file, fsynced, and only then linked
	// into place. os.Link fails if the name already exists, so it is the
	// exclusive create -- and because the name only ever appears pointing at a
	// fully written file, no racer and no crash can ever observe (or leave) an
	// empty or partial identity.
	tmp, err := os.CreateTemp(dataDir, ".installation_id-*")
	if err != nil {
		return "", fmt.Errorf("daemonmeta: stage installation identity: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()
	_, werr := tmp.WriteString(id + "\n")
	serr := tmp.Sync()
	cerr := tmp.Close()
	if err := errors.Join(werr, serr, cerr); err != nil {
		return "", fmt.Errorf("daemonmeta: write installation identity: %w", err)
	}
	if err := os.Chmod(tmpName, 0o600); err != nil {
		return "", fmt.Errorf("daemonmeta: protect installation identity: %w", err)
	}
	if err := os.Link(tmpName, path); err != nil {
		if errors.Is(err, os.ErrExist) {
			// Somebody else linked theirs first; it is complete by construction.
			return readInstallationID(path)
		}
		return "", fmt.Errorf("daemonmeta: publish installation identity: %w", err)
	}
	syncDir(dataDir)
	return id, nil
}

// syncDir makes the new directory entry durable where the platform supports it.
func syncDir(dir string) {
	if d, err := os.Open(dir); err == nil {
		_ = d.Sync()
		_ = d.Close()
	}
}

func readInstallationID(path string) (string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	id := strings.TrimSpace(string(b))
	if !ValidInstallationID(id) {
		return "", fmt.Errorf("daemonmeta: installation identity at %s is malformed; refusing to replace it", path)
	}
	return id, nil
}

// NewDaemonInstanceID mints one daemon process lifetime's identity.
func NewDaemonInstanceID() string {
	return "aod-" + uuid.NewString()
}
